/** Table of Contents definitions for each doc page's right-side navigation. */
export const TOCS: Record<string, { id: string; label: string; level?: number }[]> = {
  introduction: [
    { id: "what-is", label: "What is the Workflow Engine?" },
    { id: "who-for", label: "Who is this for?" },
    { id: "base-url", label: "Base URL & Auth" },
  ],
  architecture: [
    { id: "diagram", label: "Architecture Diagram" },
    { id: "layers", label: "Service Layers" },
    { id: "database", label: "Database Schema" },
  ],
  "core-concepts": [
    { id: "master",         label: "Workflow Master" },
    { id: "version",        label: "Workflow Version" },
    { id: "instance",       label: "Workflow Instance" },
    { id: "task",           label: "Workflow Task" },
    { id: "businesskey",    label: "Business Key" },
    { id: "processmapping", label: "Process Mapping" },
    { id: "roleregistry",   label: "Role Registry" },
  ],
  lifecycle: [
    { id: "phases",   label: "Phase Overview" },
    { id: "steps",    label: "Step by Step" },
    { id: "sequence", label: "Sequence Diagram" },
  ],
  "api-auth": [
    { id: "how-it-works",   label: "How Authentication Works" },
    { id: "sending-token",  label: "Sending the Token", level: 3 },
    { id: "signup",         label: "Sign Up" },
    { id: "login",          label: "Log In" },
    { id: "me",             label: "Current User" },
    { id: "error-envelope", label: "Error Envelope" },
  ],
  "api-definition": [
    { id: "create-master",          label: "Create Workflow Master" },
    { id: "create-definition",      label: "Create Workflow Definition" },
    { id: "get-definition",         label: "Get Definition by ID" },
    { id: "validate",               label: "Validate Definition" },
    { id: "activate",               label: "Activate Version" },
    { id: "list-masters",           label: "List All Masters" },
    { id: "get-master",             label: "Get Master with Versions" },
    { id: "available-actions",      label: "Available Actions (Def.)" },
    { id: "conditional-keys",       label: "Get Conditional Keys" },
    { id: "create-version",         label: "Create New Version" },
    { id: "toggle-status",          label: "Toggle Master Status" },
    { id: "active-instance-counts", label: "Active Instance Counts" },
    { id: "pending-instances",      label: "Check Pending Instances" },
    { id: "delete-master",          label: "Delete Master" },
    { id: "delete-version",         label: "Delete Version" },
  ],
  "api-runtime": [
    { id: "dropdown",          label: "Workflow Dropdown" },
    { id: "start",             label: "Start Workflow (processCode)" },
    { id: "instance-by-id",    label: "Get Instance by ID" },
    { id: "all-instances",     label: "Get All Instances" },
    { id: "instance-by-record",label: "Get Instance by Record" },
    { id: "tasks-pending",     label: "Pending Tasks (Direct)" },
    { id: "pending-tasks",     label: "My Pending Tasks (JWT)" },
    { id: "get-actions",       label: "Get Available Actions" },
    { id: "tasks-execute",     label: "Execute Task (Direct)" },
    { id: "execute-action",    label: "Execute Action (JWT)" },
    { id: "dashboard-stats",   label: "Dashboard Stats" },
    { id: "history",           label: "Workflow History" },
    { id: "recent-activities", label: "Recent Activities" },
    { id: "my-submissions",    label: "My Submissions" },
    { id: "diagnostic",        label: "Diagnostic" },
  ],
  "api-mapping": [
    { id: "list-processes",  label: "List Process Mappings" },
    { id: "create-process",  label: "Create Process Mapping" },
    { id: "update-process",  label: "Update Process Config" },
    { id: "delete-process",  label: "Delete Process Mapping" },
    { id: "sync-roles",      label: "Sync Roles" },
    { id: "list-roles",      label: "List Roles & Users" },
  ],
  schema: [
    { id: "top-level",   label: "Top-Level Structure" },
    { id: "node-types",  label: "Node Types" },
    { id: "node-schema", label: "Full Node Schema" },
    { id: "connections", label: "Connection Schema" },
    { id: "minimal",     label: "Minimal Example" },
  ],
  example: [
    { id: "overview",    label: "Overview" },
    { id: "step-roles",  label: "Step 1 — Sync Roles" },
    { id: "step-create", label: "Step 2 — Create Workflow" },
    { id: "step-start",  label: "Step 3 — Start Instance" },
    { id: "step-manager",label: "Step 4 — Manager Acts" },
    { id: "step-hr",     label: "Step 5 — HR Acts" },
    { id: "step-history",label: "Step 6 — Audit Trail" },
  ],
  sla: [
    { id: "config",       label: "SLA Configuration" },
    { id: "types",        label: "Escalation Types" },
    { id: "sla-response", label: "SLA Status Response" },
    { id: "ui",           label: "UI Integration" },
  ],
  troubleshooting: [
    { id: "errors", label: "Common Errors" },
    { id: "debug",  label: "Debugging Guide" },
  ],
  cheatsheet: [
    { id: "api-table",     label: "Quick API Table" },
    { id: "checklist",     label: "Integration Checklist" },
    { id: "status-codes",  label: "HTTP Status Codes" },
  ],
};
